CREATE OR REPLACE PROCEDURE EJ4 (NEMP IN EMPLEAD.NUMEMP%TYPE)
IS
EMP EMPLEAD%ROWTYPE;
JEFEOF OFICINAS.DIRECTOR%TYPE;
BEGIN
	SELECT * INTO EMP FROM EMPLEAD WHERE NEMP=NUMEMP AND CARGO NOT LIKE'Director General';
	SELECT DIRECTOR INTO JEFEOF FROM OFICINAS WHERE NEMP=EMP.NUMEMP AND NUMOFI=EMP.NUMOFI;
		
	DELETE FROM EMPLEAD
	WHERE EMP.NUMEMP=NUMEMP;
	
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('EL EMPLEADO NO EXISTE O ES DIRECTOR DIRECTOR GENERAL');
	WHEN OTHERS THEN
		IF(EMP.CARGO LIKE 'Director Ventas') THEN
		UPDATE EMPLEAD
		SET JEFE=JEFEOF
		WHERE JEFE=NEMP;
	ELSE DBMS_OUTPUT.PUT_LINE('ERROR DE BORRADO');
	END IF;
END EJ4;
/

