CREATE OR REPLACE PROCEDURE EJ1
IS
	CURSOR C1 IS
	SELECT E.NUMOFI, CIUDAD, COUNT(NUMEMP) CONT
	FROM OFICINAS O, EMPLEAD E
	WHERE O.NUMOFI=E.NUMOFI
	GROUP BY E.NUMOFI, CIUDAD;
	
	R1 C1%ROWTYPE;
BEGIN
	OPEN C1;
	
	LOOP
	FETCH C1 INTO R1;
	DBMS_OUTPUT.PUT_LINE(R1.NUMOFI||' - '||R1.CIUDAD||' - '||R1.CONT);
		EXIT WHEN(C1%NOTFOUND);
	END LOOP;
	CLOSE C1;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO HAY OFICINAS INSERTADAS');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR');
END EJ1;
/


