CREATE OR REPLACE PROCEDURE EJ3 (NOF IN OFICINAS.NUMOFI%TYPE)
IS
	CURSOR C1 IS
	SELECT NOMAPE, CARGO, CONTRATO
	FROM EMPLEAD
	WHERE NOF=NUMOFI;
	
	R1 C1%ROWTYPE; 
	
	ANIOS NUMBER:=0;
	NO_EX EXCEPTION;
BEGIN
	OPEN C1;
	FETCH C1 INTO R1;
	IF(C1%NOTFOUND) THEN 
			RAISE NO_EX;
	ELSE
		WHILE (C1%FOUND) LOOP
			ANIOS:=EJ2(R1.CONTRATO);
			DBMS_OUTPUT.PUT_LINE(R1.NOMAPE||'-'||R1.CARGO||'-'||ANIOS);
			FETCH C1 INTO R1;		
		END LOOP;
	END IF;
	CLOSE C1;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DBMS_OUTPUT.PUT_LINE('NO EXISTE LA OFICINA');
	WHEN NO_EX THEN
		DBMS_OUTPUT.PUT_LINE('NO EXISTEN EMPLEADOS O OFICINA');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR');
END EJ3;
/
