DROP TABLE DIRECTOR CASCADE CONSTRAINTS;
CREATE TABLE DIRECTOR (
	COD_Director NUMBER(20) PRIMARY KEY,
	Nombre VARCHAR2(20) not null,
	Titulacion VARCHAR2(20) not null,
	Fecha_Nac DATE,
	Dirección VARCHAR2(25),
	CONSTRAINT CK_TITU CHECK (Titulacion IN ('Máster Univesit.','Grado en Música')));

DROP TABLE ORQUESTA CASCADE CONSTRAINTS;
CREATE TABLE ORQUESTA (
	COD_Orquesta NUMBER(20) PRIMARY KEY,
	COD_Director NUMBER(20) unique not null,
	Nombre VARCHAR2(20),
	N_Componentes Number(20),
	Dirección_Ads VARCHAR2(25),
	Fecha_INS Date,
	CONSTRAINT CK_Comp CHECK (N_Componentes<100 OR N_Componentes>20),
	CONSTRAINT FK_ORQ FOREIGN KEY (COD_Director) REFERENCES DIRECTOR (COD_Director));
	
DROP TABLE SOLISTA CASCADE CONSTRAINTS;
CREATE TABLE SOLISTA (
	COD_Solista NUMBER(20) PRIMARY KEY,
	Nombre VARCHAR2(20),
	Instrumento VARCHAR2(20),
	Fecha_Nac Date);

DROP TABLE COMPOSITOR CASCADE CONSTRAINTS;
CREATE TABLE COMPOSITOR (
	COD_Compositor NUMBER(20) PRIMARY KEY,
	Nombre VARCHAR2(20),
	N_Obras NUMBER(20),
	Fecha_Nac DATE,
	Fecha_Def DATE);

DROP TABLE CONCIERTO CASCADE CONSTRAINTS;
CREATE TABLE CONCIERTO (
	COD_Concierto NUMBER(20),
	COD_Orquesta NUMBER(20) not null,
	Nombre VARCHAR2(25),
	Fecha DATE,
	CONSTRAINT PK_CONCIERTO PRIMARY KEY (COD_Concierto, Fecha),
	CONSTRAINT FK_CONCIERTO FOREIGN KEY (COD_Orquesta) REFERENCES ORQUESTA (COD_Orquesta));

DROP TABLE OBRA CASCADE CONSTRAINTS;
CREATE TABLE OBRA (
	COD_Obra NUMBER(20) PRIMARY KEY,
	COD_Compositor NUMBER(20) not null,
	Titulo VARCHAR2(25) UNIQUE not null,
	CONSTRAINT FK_OBRA FOREIGN KEY (COD_Compositor) REFERENCES COMPOSITOR (COD_Compositor));

DROP TABLE INTERPRETACION CASCADE CONSTRAINTS;
CREATE TABLE INTERPRETACION (
	COD_Concierto NUMBER(20),
	COD_Obra NUMBER(20),
	COD_Solista NUMBER(20),
	Fecha DATE,
	CONSTRAINT PK_ITERPRETA PRIMARY KEY (COD_Concierto, COD_Obra, Fecha),
	CONSTRAINT FK_INTERPRETA1 FOREIGN KEY (COD_Concierto, Fecha) REFERENCES CONCIERTO (COD_Concierto, Fecha),
	CONSTRAINT FK_INTERPRETA2 FOREIGN KEY (COD_Obra) REFERENCES OBRA (COD_Obra),
	CONSTRAINT FK_INTERPRETA3 FOREIGN KEY (COD_Solista) REFERENCES SOLISTA (COD_Solista));

DROP TABLE INVITADO CASCADE CONSTRAINTS;
CREATE TABLE INVITADO (
	COD_Director NUMBER(20),
	COD_Orquesta NUMBER(20),
	Fecha DATE,
	CONSTRAINT PK_INVITADO PRIMARY KEY (COD_Director, COD_Orquesta, Fecha),
	CONSTRAINT FK_INVITADO1 FOREIGN KEY (COD_Director) REFERENCES DIRECTOR (COD_Director),
	CONSTRAINT FK_INVITADO2 FOREIGN KEY (COD_Orquesta) REFERENCES ORQUESTA (COD_Orquesta));
