CREATE OR REPLACE FUNCTION DIAS_INV (INV DIRECTOR.NOMBRE%TYPE)
RETURN NUMBER
IS
I_REG INVITADO%ROWTYPE;
I_DIAS NUMBER;
BEGIN
	SELECT I.COD_DIRECTOR, I.COD_ORQUESTA, FECHA INTO I_REG 
	FROM INVITADO I, DIRECTOR D 
	WHERE NOMBRE LIKE INV AND I.COD_DIRECTOR=D.COD_DIRECTOR 
	AND I.FECHA=(SELECT MAX(FECHA) FROM INVITADO I, DIRECTOR D 
	WHERE NOMBRE LIKE INV AND D.COD_DIRECTOR=I.COD_DIRECTOR);
	
	I_DIAS:=trunc((sysdate-I_REG.FECHA));
	
	RETURN I_DIAS;
END DIAS_INV;
/

CREATE OR REPLACE FUNCTION SOL_CON (SOL SOLISTA.NOMBRE%TYPE)
RETURN NUMBER
IS
N_CONC NUMBER;
BEGIN
	SELECT COUNT(*) INTO N_CONC 
	FROM INTERPRETACION I, CONCIERTO C, SOLISTA S 
	WHERE S.COD_SOLISTA=I.COD_SOLISTA AND C.COD_CONCIERTO=I.COD_CONCIERTO 
	AND S.NOMBRE LIKE SOL;
	
	RETURN N_CONC;
END SOL_CON;
/
